/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MeskChatApplication.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { Status } from './status';

export interface ApplicationUser2 {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  username: string;
  status: Status;
  /** @nullable */
  lastOnlineAt: string | null;
}
