/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MeskChatApplication.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface PasswordResetToken {
  userId: string;
  user?: User;
  token?: string;
  expires?: string;
  isUsed?: boolean;
  /** @nullable */
  usedAt?: string | null;
  id?: string;
  isDeleted?: boolean;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  deletedAt?: string | null;
}
