/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MeskChatApplication.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterCommand {
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  password: string;
}
