/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MeskChatApplication.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RefreshTokenCommandResponse } from './refreshTokenCommandResponse';
import type { ResponseEntityOfRefreshTokenCommandResponseValidationErrors } from './responseEntityOfRefreshTokenCommandResponseValidationErrors';

export interface ResponseEntityOfRefreshTokenCommandResponse {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
  data?: RefreshTokenCommandResponse;
  statusCode?: number;
  /** @nullable */
  validationErrors?: ResponseEntityOfRefreshTokenCommandResponseValidationErrors;
}
