/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MeskChatApplication.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ResponseEntityOfstringValidationErrors } from './responseEntityOfstringValidationErrors';

export interface ResponseEntityOfstring {
  isSuccess?: boolean;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  data?: string | null;
  statusCode?: number;
  /** @nullable */
  validationErrors?: ResponseEntityOfstringValidationErrors;
}
