/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * MeskChatApplication.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { NullableOfStatus } from './nullableOfStatus';
import type { RefreshToken } from './refreshToken';
import type { PasswordResetToken } from './passwordResetToken';

export interface User {
  /**
   * @minLength 3
   * @maxLength 30
   */
  firstName: string;
  /**
   * @minLength 3
   * @maxLength 30
   */
  lastName: string;
  email: string;
  /**
   * @minLength 3
   * @maxLength 30
   */
  username: string;
  passwordHash?: string;
  passwordSalt?: string;
  status?: NullableOfStatus;
  /** @nullable */
  lastOnlineAt?: string | null;
  /** @nullable */
  profilePhotoUrl?: string | null;
  refreshTokens?: RefreshToken[];
  passwordResetTokens?: PasswordResetToken[];
  id?: string;
  isDeleted?: boolean;
  createdAt?: string;
  /** @nullable */
  updatedAt?: string | null;
  /** @nullable */
  deletedAt?: string | null;
}
